package com.example.fileparser.repositories;

import com.example.fileparser.models.Metadata;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface MetadataRepository extends MongoRepository<Metadata, String> {

    // find all metadata ever generated by a user
    Optional<List<Metadata>> findByUserId(String userId);

    // find the metadata for a specific file
    Optional<Metadata> findByFileId(String fileId);
}
